services:
  yugabyte:
    image: yugabytedb/yugabyte:2.25.2.0-b359
    ports:
      - "7001:7000"
      - "9200:9000"
      - "15433:15433"
      - "5433:5433"
      - "9042:9042"
    volumes:
      - yb_data:/root/var
    environment:
      YSQL_DB: auroragw
    command: >
      bin/yugabyted start
        --background=false
        --advertise_address=yugabyte
  minio:
    image: minio/minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=adminadmin
      - MINIO_VOLUMES="/mnt/data"
    volumes:
      - minio_data:/mnt/data
    ports:
      - "9000:9000"
      - "9001:9001"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: server --console-address ":9001"
volumes:
  yb_data:
  minio_data: