name: Go Test

on:
  pull_request:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  checks: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event_name == 'push' && github.sha || github.ref }}
  cancel-in-progress: true

jobs:
  go-test:
    runs-on: ${{ vars.TESTS_RUNNER }}
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        env:
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
        if: ${{ env.DOCKER_HUB_TOKEN != '' }}
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Download base images
        run: |
          docker pull golang:1.25-alpine
          docker pull alpine:3.22.0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25.7

      - name: Run tests
        run: |
          go mod download
          mkdir -p test-results
          set -o pipefail
          go test -p ${{ vars.TESTS_PARALLELISM }} -json ./... 2>&1 | tee test-results/test-results.json

      - name: Upload test report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: unit-test-report
          path: test-results/test-results.json

      - name: Publish Test Report
        uses: dorny/test-reporter@v2
        if: always()
        with:
          artifact: unit-test-report
          name: Go tests
          path: '*.json'
          reporter: golang-json
  go-check:
    runs-on: ${{ vars.TESTS_RUNNER }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25.7

      - name: Verify go mod tidy
        run: |
          go mod tidy
          if [[ -n $(git status --porcelain go.mod go.sum) ]]; then
            echo "::error go.mod or go.sum needs 'go mod tidy'."
            git --no-pager diff
            exit 1
          fi

      - name: Verify go fmt
        if: always()
        run: |
          out=$(gofmt -s -l .)
          if [[ -n "$out" ]]; then
            echo "Files is not gofmt-ed."
            echo $out
            exit 1
          fi

      - name: Verify go vet
        if: always()
        run: go vet ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        if: always()
        with:
          version: v2.1
          only-new-issues: 'true'
